#!/bin/bash
sed -i 's/if (currentRoute != Screen.Extensions.route) {/navController.navigate(Screen.Extensions.route) {\n                                popUpTo(navController.graph.startDestinationId) { saveState = true }\n                                launchSingleTop = true\n                                restoreState = true\n                            }\n                            \/\//g' app/src/main/java/com/example/navigation/AppNavigation.kt

sed -i 's/if (currentRoute != Screen.Social.route) {/navController.navigate(Screen.Social.route) {\n                                popUpTo(navController.graph.startDestinationId) { saveState = true }\n                                launchSingleTop = true\n                                restoreState = true\n                            }\n                            \/\//g' app/src/main/java/com/example/navigation/AppNavigation.kt

sed -i 's/if (currentRoute != Screen.Share.route) {/navController.navigate(Screen.Share.route) {\n                                popUpTo(navController.graph.startDestinationId) { saveState = true }\n                                launchSingleTop = true\n                                restoreState = true\n                            }\n                            \/\//g' app/src/main/java/com/example/navigation/AppNavigation.kt

sed -i 's/if (currentRoute == Screen.Downloads.route) {/navController.navigate(Screen.Downloads.route) {\n                                popUpTo(navController.graph.startDestinationId) { saveState = true }\n                                launchSingleTop = true\n                                restoreState = true\n                            }\n                            \/\//g' app/src/main/java/com/example/navigation/AppNavigation.kt

sed -i 's/if (currentRoute == Screen.About.route) {/navController.navigate(Screen.About.route) {\n                                popUpTo(navController.graph.startDestinationId) { saveState = true }\n                                launchSingleTop = true\n                                restoreState = true\n                            }\n                            \/\//g' app/src/main/java/com/example/navigation/AppNavigation.kt
