translation_dict = {
    r"""$0.00 / month""": ("name", "", ""),
    r"""$9.99 / month""": ("name", "", ""),
    r"""$availableStr free""": ("name", "", ""),
    r"""$selectedStat Activity""": ("name", "", ""),
    r"""$type • $size""": ("name", "", ""),
    r"""$usedPercentageInt% used""": ("name", "", ""),
    r"""$usedStr / $totalStr used""": ("name", "", ""),
    r"""$year • ${if(isMovie) stringResource(R.string.movie_singular) else stringResource(R.string.series_singular)}""": ("name", "", ""),
    r"""${(item.progress * 100).toInt()}%""": ("name", "", ""),
    r"""${episode.duration}m""": ("name", "", ""),
    r"""${episode.episodeNumber}. ${episode.title}""": ("name", "", ""),
    r"""${groupedSeries[folderName]?.size ?: 0} Episodes""": ("name", "", ""),
    r"""${movie.year} • ${movie.genres.take(3).joinToString(""": ("name", "", ""),
    r"""${series.year} • ${series.genres.take(3).joinToString(""": ("name", "", ""),
    r"""@${currentUser?.username}""": ("name", "", ""),
    r"""@${userProfile!!.username}""": ("name", "", ""),
    r"""A group of men fight for survival in a world where trust is a luxury.""": ("name", "", ""),
    r"""About""": ("name", "", ""),
    r"""About CineStream""": ("name", "", ""),
    r"""Account""": ("name", "", ""),
    r"""Active Devices""": ("name", "", ""),
    r"""Active now • Riyadh, KSA""": ("name", "", ""),
    r"""Add Story""": ("name", "", ""),
    r"""Allow others to search for you and see your profile""": ("name", "", ""),
    r"""Android • Ready to connect""": ("name", "", ""),
    r"""App Crashed!""": ("name", "", ""),
    r"""App Settings""": ("name", "", ""),
    r"""Are you sure you want to sign out?""": ("name", "", ""),
    r"""Available Devices:""": ("name", "", ""),
    r"""Back to Folders""": ("name", "", ""),
    r"""Basic""": ("name", "", ""),
    r"""Batch Download - ${currentSeason?.seasonNumber?.let { """: ("name", "", ""),
    r"""Biography""": ("name", "", ""),
    r"""Birthplace""": ("name", "", ""),
    r"""Born""": ("name", "", ""),
    r"""Browse by Category""": ("name", "", ""),
    r"""C""": ("name", "", ""),
    r"""Cancel""": ("name", "", ""),
    r"""Change Password""": ("name", "", ""),
    r"""Choose Content Type""": ("name", "", ""),
    r"""Choose Your Plan""": ("name", "", ""),
    r"""CineStream""": ("name", "", ""),
    r"""CineStream Community""": ("name", "", ""),
    r"""CineStream is your premium cinematic experience. Stream your favorite movies and series in high quality, anytime, anywhere.""": ("name", "", ""),
    r"""Completed""": ("name", "", ""),
    r"""Connect""": ("name", "", ""),
    r"""Connected to ${connectedEndpoint!!.name}""": ("name", "", ""),
    r"""Connected to ${connectedEndpoint?.name}""": ("name", "", ""),
    r"""Connecting to ${uiState.currentWebsite}$serverText...""": ("name", "", ""),
    r"""Connection Status""": ("name", "", ""),
    r"""Control what visitors can see about your profile.""": ("name", "", ""),
    r"""Copy""": ("name", "", ""),
    r"""Copy Error""": ("name", "", ""),
    r"""Crash Error""": ("name", "", ""),
    r"""Current Password""": ("name", "", ""),
    r"""Current Plan""": ("name", "", ""),
    r"""Current Site: ${uiState.currentWebsite}""": ("name", "", ""),
    r"""Delete""": ("name", "", ""),
    r"""Delete Message""": ("name", "", ""),
    r"""Delete for Everyone""": ("name", "", ""),
    r"""Delete for Me""": ("name", "", ""),
    r"""Do you want to set this as your new profile picture?""": ("name", "", ""),
    r"""Download (${selectedEpisodes.size})""": ("name", "", ""),
    r"""Edit""": ("name", "", ""),
    r"""Edit Profile""": ("name", "", ""),
    r"""Edited""": ("name", "", ""),
    r"""Email (Gmail)""": ("name", "", ""),
    r"""Enjoy ad-free streaming and exclusive content.""": ("name", "", ""),
    r"""Enter your email""": ("name", "", ""),
    r"""Ep ${episode.episodeNumber}: ${episode.title}""": ("name", "", ""),
    r"""Episode ${ep.episodeNumber}: ${ep.title}""": ("name", "", ""),
    r"""Episodes""": ("name", "", ""),
    r"""First Name""": ("name", "", ""),
    r"""Forgot Password?""": ("name", "", ""),
    r"""G """: ("name", "", ""),
    r"""HD""": ("name", "", ""),
    r"""How it works?""": ("name", "", ""),
    r"""Known For""": ("name", "", ""),
    r"""Last Name""": ("name", "", ""),
    r"""Last active: Yesterday • Riyadh, KSA""": ("name", "", ""),
    r"""Loading ${uiState.currentWebsite}$serverText...""": ("name", "", ""),
    r"""Looking for devices...""": ("name", "", ""),
    r"""MacBook Air""": ("name", "", ""),
    r"""Make sure both devices have Wi-Fi and are close to each other. Large files may take some time to transfer.""": ("name", "", ""),
    r"""Make sure the sender is on the same Wi-Fi network or Bluetooth is enabled. Transfer uses high-speed Wi-Fi Direct.""": ("name", "", ""),
    r"""Manage Plan""": ("name", "", ""),
    r"""Messages are end-to-end encrypted.\nYour privacy is our priority.""": ("name", "", ""),
    r"""Movies""": ("name", "", ""),
    r"""Nearby Devices""": ("name", "", ""),
    r"""New Password""": ("name", "", ""),
    r"""No downloaded movies found.""": ("name", "", ""),
    r"""Offline Share""": ("name", "", ""),
    r"""Online""": ("name", "", ""),
    r"""Or continue with""": ("name", "", ""),
    r"""POPULAR""": ("name", "", ""),
    r"""Password""": ("name", "", ""),
    r"""Play Now""": ("name", "", ""),
    r"""Preferences""": ("name", "", ""),
    r"""Premium Member""": ("name", "", ""),
    r"""Premium Plan""": ("name", "", ""),
    r"""Premium 👑""": ("name", "", ""),
    r"""Privacy Settings""": ("name", "", ""),
    r"""Profile""": ("name", "", ""),
    r"""Public Profile""": ("name", "", ""),
    r"""Quality""": ("name", "", ""),
    r"""Quality:""": ("name", "", ""),
    r"""R""": ("name", "", ""),
    r"""Ready to Play""": ("name", "", ""),
    r"""Ready to receive""": ("name", "", ""),
    r"""Receive Content""": ("name", "", ""),
    r"""Receive Media""": ("name", "", ""),
    r"""Receive from nearby devices""": ("name", "", ""),
    r"""Recent Transfers""": ("name", "", ""),
    r"""Remember me""": ("name", "", ""),
    r"""Reset Password""": ("name", "", ""),
    r"""Restart App""": ("name", "", ""),
    r"""Results for \""": ("name", "", ""),
    r"""Save""": ("name", "", ""),
    r"""Save Changes""": ("name", "", ""),
    r"""Scan""": ("name", "", ""),
    r"""Search by username to message...""": ("name", "", ""),
    r"""Searching for video...""": ("name", "", ""),
    r"""Security""": ("name", "", ""),
    r"""Select Download Quality""": ("name", "", ""),
    r"""Select Quality""": ("name", "", ""),
    r"""Select Server""": ("name", "", ""),
    r"""Select Server & Quality""": ("name", "", ""),
    r"""Select Source Website""": ("name", "", ""),
    r"""Send""": ("name", "", ""),
    r"""Send Content""": ("name", "", ""),
    r"""Series / Anime""": ("name", "", ""),
    r"""Share movies, series or anime""": ("name", "", ""),
    r"""Sign Out""": ("name", "", ""),
    r"""Sign in to chat and share with others""": ("name", "", ""),
    r"""Sign in with Google""": ("name", "", ""),
    r"""Sign out""": ("name", "", ""),
    r"""Skip""": ("name", "", ""),
    r"""Source:""": ("name", "", ""),
    r"""Stories""": ("name", "", ""),
    r"""Subscription""": ("name", "", ""),
    r"""This account is private.""": ("name", "", ""),
    r"""Tips for faster transfer""": ("name", "", ""),
    r"""Today""": ("name", "", ""),
    r"""Update Password""": ("name", "", ""),
    r"""Update Profile Picture""": ("name", "", ""),
    r"""Upgrade to Premium""": ("name", "", ""),
    r"""Upgrade to Premium to unlock all features""": ("name", "", ""),
    r"""User not found""": ("name", "", ""),
    r"""Username""": ("name", "", ""),
    r"""View All""": ("name", "", ""),
    r"""View all""": ("name", "", ""),
    r"""Waiting for action""": ("name", "", ""),
    r"""Waiting for files...""": ("name", "", ""),
    r"""Welcome to""": ("name", "", ""),
    r"""Who do you want to delete this message for?""": ("name", "", ""),
    r"""You're Premium!""": ("name", "", ""),
    r"""Your Cinematic World, Anytime, Anywhere.""": ("name", "", ""),
    r"""Your ultimate destination for\nmovies and series. Enjoy endless\nentertainment, anytime, anywhere.""": ("name", "", ""),
    r"""iPhone 13 Pro""": ("name", "", ""),
    r"""message""": ("name", "", ""),
    r"""username""": ("name", "", ""),
    r"""إدارة مصادر المشاهدة واستمتع بمحتوى أكثر""": ("name", "", ""),
    r"""إعادة الفحص""": ("name", "", ""),
    r"""إعادة المحاولة""": ("name", "", ""),
    r"""إعادة المحاولة مجدداً""": ("name", "", ""),
    r"""إعادة محاولة استخراج الجودات""": ("name", "", ""),
    r"""إلغاء""": ("name", "", ""),
    r"""إلغاء التثبيت""": ("name", "", ""),
    r"""إلغاء العملية""": ("name", "", ""),
    r"""إلغاء تماماً""": ("name", "", ""),
    r"""اختر الجودة ($selectedServerForQuality)""": ("name", "", ""),
    r"""اختر السيرفر""": ("name", "", ""),
    r"""اسحب للأعلى لتحميل المزيد""": ("name", "", ""),
    r"""الإضافات""": ("name", "", ""),
    r"""الانتقال إلى الإضافات""": ("name", "", ""),
    r"""البحث في الإضافات...""": ("name", "", ""),
    r"""البحث في موقع آخر""": ("name", "", ""),
    r"""الرجاء الإنتظار، يتم جلب أحدث المعلومات من السيرفرات.""": ("name", "", ""),
    r"""السيرفر: $selectedServerForQuality""": ("name", "", ""),
    r"""العملية لا تزال جارية، هل أنت متأكد أنك تريد الإلغاء؟""": ("name", "", ""),
    r"""العودة لاختيار سيرفر آخر""": ("name", "", ""),
    r"""تأكيد""": ("name", "", ""),
    r"""تأكيد التخطي""": ("name", "", ""),
    r"""تأكيد فتح المتصفح""": ("name", "", ""),
    r"""تثبيت""": ("name", "", ""),
    r"""تحميل المزيد من الحلقات""": ("name", "", ""),
    r"""تخطي الموقع الحالي""": ("name", "", ""),
    r"""تم التحقق، متابعة""": ("name", "", ""),
    r"""تم جلب السيرفرات من: $currentSiteName""": ("name", "", ""),
    r"""تم حذف هذه الرسالة""": ("name", "", ""),
    r"""جاري الإتصال بالسيرفرات المتاحة...""": ("name", "", ""),
    r"""جاري تحميل الحلقات...""": ("name", "", ""),
    r"""حدث خطأ في الاتصال بالإنترنت""": ("name", "", ""),
    r"""روابط التحميل المباشرة""": ("name", "", ""),
    r"""صفحة الإضافات""": ("name", "", ""),
    r"""عذراً، لم نتمكن من العثور على سيرفرات تعمل لهذا العمل في جميع المواقع المدعومة.""": ("name", "", ""),
    r"""فتح المتصفح يدوياً للتحقق""": ("name", "", ""),
    r"""فشل في العثور على أي جودة""": ("name", "", ""),
    r"""لا توجد إضافات أخرى""": ("name", "", ""),
    r"""لم يتم تثبيت أي إضافات""": ("name", "", ""),
    r"""لم يتم تثبيت أي إضافات أخرى للمتابعة. ماذا تريد أن تفعل؟""": ("name", "", ""),
    r"""متابعة""": ("name", "", ""),
    r"""ملاحظة""": ("name", "", ""),
    r"""نعم""": ("name", "", ""),
    r"""نعم، أكمل""": ("name", "", ""),
    r"""نعم، إلغاء""": ("name", "", ""),
    r"""هل أنت متأكد أنك قمت بتخطي حماية Cloudflare بنجاح؟""": ("name", "", ""),
    r"""هل أنت متأكد من رغبتك في تخطي هذا الموقع والانتقال للتالي؟""": ("name", "", ""),
    r"""هل أنت متأكد من رغبتك في فتح المتصفح يدوياً للتحقق من الرابط؟""": ("name", "", ""),
    r"""يرجى التحقق من الشبكة والمحاولة مرة أخرى.""": ("name", "", ""),
    r"""يرجى تثبيت إضافة واحدة على الأقل لجلب الخوادم والروابط.""": ("name", "", ""),
    r"""يرجى تخطي الحماية للمتابعة...""": ("name", "", ""),
    r"""يمكنك تثبيت عدة إضافات للحصول على تجربة مشاهدة أفضل ومصادر أكثر.""": ("name", "", ""),
}
